services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.backend
    env_file: ./backend/.env
    environment:
      STATIC_ROOT: /app/staticfiles
      MEDIA_ROOT: /app/media
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "127.0.0.1:8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./staticfiles:/static:ro
      - ./media:/media:ro
    restart: unless-stopped
