networks:
  app-net:

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.backend
    env_file: ./backend/.env
    environment:
      STATIC_ROOT: /app/staticfiles
      MEDIA_ROOT: /app/media
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./backend/db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    restart: unless-stopped
    networks: [app-net]

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.frontend
    depends_on:
      - backend
    expose:
      - "80"
    restart: unless-stopped
    networks: [app-net]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/static:ro
      - ./media:/media:ro
    restart: unless-stopped
    networks: [app-net]
