# Generated by Django 3.2.15 on 2025-06-12 16:03

from django.db import migrations


def fill_orderitem_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.select_related('product'):
        item.price = item.product.price
        item.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_orderitem_prices, reverse_code=migrations.RunPython.noop),
    ]
