# Generated by Django 3.2.15 on 2025-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('cooking', 'Готовится'), ('delivering', 'Доставляется'), ('done', 'Выполнен')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
    ]
